<a href="https://colab.research.google.com/github/RohitKarake/pytorch_tutorials/blob/main/pytorch_getting_started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
import numpy as np

### Numpy Array

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.78654128, 0.94195618, 0.5612912 , 0.90656505],
       [0.8919695 , 0.69219648, 0.45128764, 0.82027373],
       [0.98635014, 0.24401137, 0.72746782, 0.57791068]])

In [5]:
np1.dtype

dtype('float64')

### Tenosrs

In [10]:
tensor_2d = torch.randn(3,4)
print(tensor_2d.dtype)
tensor_2d


torch.float32


tensor([[-1.7391, -0.7530, -0.7060,  2.1623],
        [-0.0656, -0.3475, -0.0732,  0.1985],
        [ 0.5545,  0.4258, -0.4142, -2.0385]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
### Create tensor from numpy array
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.7865, 0.9420, 0.5613, 0.9066],
        [0.8920, 0.6922, 0.4513, 0.8203],
        [0.9864, 0.2440, 0.7275, 0.5779]], dtype=torch.float64)

### Tensor Reshape

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
### If we dont know the shape
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.reshape(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch3[1] = 121
my_torch4

tensor([[  0, 121,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [19]:
my_torch5 = torch.arange(10)
my_torch5 = my_torch5.reshape(5,2)
my_torch5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
my_torch5[:, 1]

tensor([1, 3, 5, 7, 9])

In [21]:
# Return as a column
my_torch5[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

### Tensor Math Operations

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a.shape

torch.Size([4])

In [25]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [28]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [30]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [31]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [32]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [34]:
### remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [35]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [36]:
## Exponensts / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [37]:
## Reassignment_
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
tensor_a

tensor([ 6,  8, 10, 12])